const nodemailer = require('nodemailer');
const dotenv = require('dotenv');

dotenv.config();

/**
 * Email Service for Educational Purposes Only
 * 
 * This service sends simulated notification emails strictly for educational
 * and testing purposes. All emails include educational disclaimers.
 */
class EmailService {
  constructor() {
    this.educationalFooter = process.env.EDUCATIONAL_FOOTER || 
      'This is a simulation for educational purposes only.';
    
    // Initialize transporter with Ethereal (fake SMTP service for testing)
    this.transporter = null;
    this.initializeTransporter();
  }

  async initializeTransporter() {
    try {
      // Use environment variables or create test account
      if (process.env.EMAIL_HOST && process.env.EMAIL_USER) {
        this.transporter = nodemailer.createTransport({
          host: process.env.EMAIL_HOST,
          port: parseInt(process.env.EMAIL_PORT) || 587,
          secure: false,
          auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS
          }
        });
      } else {
        // Create test account for development
        const testAccount = await nodemailer.createTestAccount();
        this.transporter = nodemailer.createTransport({
          host: 'smtp.ethereal.email',
          port: 587,
          secure: false,
          auth: {
            user: testAccount.user,
            pass: testAccount.pass
          }
        });
        console.log('📧 Using Ethereal test email account:', testAccount.user);
      }
    } catch (error) {
      console.error('Failed to initialize email transporter:', error.message);
    }
  }

  /**
   * Add educational footer to email content
   */
  addEducationalFooter(htmlContent) {
    const footerHtml = `
      <div style="margin-top: 40px; padding: 20px; background-color: #fff3cd; border: 2px solid #ffc107; border-radius: 5px;">
        <p style="margin: 0; color: #856404; font-weight: bold; text-align: center;">
          ⚠️ ${this.educationalFooter}
        </p>
        <p style="margin: 10px 0 0 0; color: #856404; font-size: 12px; text-align: center;">
          This email was generated by an educational simulation platform and should not be considered legitimate correspondence.
        </p>
      </div>
    `;
    return htmlContent + footerHtml;
  }

  /**
   * Validate email options to prevent impersonation and fraud
   */
  validateEmailOptions(options) {
    const errors = [];

    // Check for forbidden keywords that might indicate impersonation
    const forbiddenKeywords = [
      'paypal', 'bank', 'venmo', 'zelle', 'cashapp',
      'amazon', 'apple', 'google', 'microsoft',
      'irs', 'government', 'federal',
      'account suspended', 'verify account', 'urgent action required',
      'click here immediately', 'confirm identity'
    ];

    const contentToCheck = (
      (options.subject || '') + ' ' +
      (options.text || '') + ' ' +
      (options.html || '')
    ).toLowerCase();

    for (const keyword of forbiddenKeywords) {
      if (contentToCheck.includes(keyword)) {
        errors.push(`Content contains forbidden keyword that may indicate impersonation: "${keyword}"`);
      }
    }

    // Ensure "to" address doesn't look like phishing
    if (options.to && options.to.includes('@')) {
      const domain = options.to.split('@')[1];
      const suspiciousDomains = ['paypal.com', 'bank.com', 'amazon.com'];
      if (suspiciousDomains.some(d => domain.includes(d))) {
        errors.push('Cannot send to domains that may enable fraud');
      }
    }

    // Ensure subject isn't misleading
    if (options.subject && options.subject.length < 5) {
      errors.push('Subject must be at least 5 characters');
    }

    return errors;
  }

  /**
   * Send educational simulation email
   */
  async sendEmail(options) {
    if (!this.transporter) {
      await this.initializeTransporter();
    }

    // Validate options
    const validationErrors = this.validateEmailOptions(options);
    if (validationErrors.length > 0) {
      throw new Error(`Validation failed: ${validationErrors.join(', ')}`);
    }

    // Prepare email with educational footer
    const mailOptions = {
      from: options.from || process.env.EMAIL_FROM || 'educational@simulation.test',
      to: options.to,
      subject: `[SIMULATION] ${options.subject}`,
      text: `${options.text}\n\n---\n${this.educationalFooter}`,
      html: options.html ? this.addEducationalFooter(options.html) : undefined
    };

    try {
      const info = await this.transporter.sendMail(mailOptions);
      console.log('✅ Simulation email sent:', info.messageId);
      
      // Return preview URL for Ethereal
      const previewUrl = nodemailer.getTestMessageUrl(info);
      
      return {
        success: true,
        messageId: info.messageId,
        previewUrl: previewUrl || null,
        disclaimer: this.educationalFooter
      };
    } catch (error) {
      console.error('❌ Failed to send email:', error.message);
      throw error;
    }
  }
}

module.exports = new EmailService();
